### ISSUE TITLE
db hint

### ISSUE THREAD

**Issue by vitaly-t** [TechMaster/pg_promise#1]
You have a problem in one of your tests...

```js
t.tx(function (t1)
```
you are creating a sub-transaction, which also returns a promise that you do not even handle, thus ending up with a loose promise on your sub-transaction call.

https://github.com/TechMaster/pg_promise/blob/master/test/09_InsertPostPageTransact.ajs#L85

**Comment by TechMaster** [comment]
Thanks vitaly-t, I will look at fix this test. Your pg-promise is good: much faster than sequelize, fully controlled SQL.

I will write some more tests to verify pg-promise.

**Comment by vitaly-t** [comment]
This also creates loose promises: https://github.com/TechMaster/pg_promise/blob/master/test/05_NestedTransaction.js#L31

**Comment by TechMaster** [comment]
Hi vitaly-t,

Can you help me out? I really get stuck with nested transaction.

Thanks,

**Comment by vitaly-t** [comment]
Ok, but what is the nature of your problem? Or do you mean, to fix that last issue I highlighted?

**Comment by TechMaster** [comment]
Yes, please show me how to fix it. I tried different approaches but it does not seem to work.

**Comment by vitaly-t** [comment]
Here's the PR: https://github.com/TechMaster/pg_promise/pull/2

**Comment by TechMaster** [comment]
Thanks vitaly-t, I have merged your pull request and push latest to github.
I will comeback with using pg-promise to implement Object speak SQL pattern
[ORM Is an Offensive Anti-Pattern](http://www.yegor256.com/2014/12/01/orm-offensive-anti-pattern.html)
